Fixed jwt auth, connected checkout with psp from webshop
mas-projekti/SEP_Projekat pull request #16
Opened 2022-01-08 22:49 UTC by lemara98

2022-01-08 22:51 UTC, lemara98 commented
![image](https://user-images.githubusercontent.com/58090742/148662495-c08e7946-eba8-4db2-974d-122a21db1608.png)
![image](https://user-images.githubusercontent.com/58090742/148662508-c0942f92-36ac-4edd-9569-b61b3186d2bc.png)

2022-01-08 22:55 UTC, lemara98 commented
Da li da ga mrdzujemo prvo na webshop, ili direktno na develop?

2022-01-10 16:59 UTC, AnLong98 commented
Stavicemo na develop pa sta mu Bog da.

2022-01-10 17:09 UTC, AnLong98 requested changes
Napisi molim te ovde odgovore ili zovni na skajp.

2022-01-10 17:09 UTC, AnLong98 commented on PSP.API/Services/TransactionService.cs
> +            Guid newGuid = Guid.NewGuid();
Ovaj kod mi nije jasan. Sta ovo radi i zasto si menjao PSP API? Osim toga GUID ne bi trebao ti da pravis vec se on sam napravi koliko se secam od strane baze.

2022-01-10 17:09 UTC, AnLong98 commented on WebShop/WebShop.Frontend/Frontend/src/pages/Cart.js
> +    const merchantId = decodedToken[`http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata`];
Otkad je merchant ID u tokenu?

2022-01-10 17:09 UTC, AnLong98 commented on WebShop/WebShop.Frontend/Frontend/src/pages/Cart.js
> +    axios.post(`${BASE_URL}/payment-service/transactions`, listOfOrders, config)
Ja bih rekao da ovo nije dobro. Ti kad neko nesto kupuje pravis samo jedan order, i to tako sto PSP-u posaljes objekat order dto.

2022-01-10 17:09 UTC, AnLong98 commented on WebShop/WebShop.Service/Services/UserService.cs
> +                new Claim(ClaimTypes.UserData, userDTO.MerchantId)
Ok sad vidim odakle merchantID. Al sad mi nije jasno, ako se ja prijavim kao obican kupac, onda ces ti iz mog tokena vaditi merchantID? Kako ovo funkcionise?

2022-01-10 17:22 UTC, lemara98 commented on PSP.API/Services/TransactionService.cs
> +            Guid newGuid = Guid.NewGuid();
У обрисаном случају се увек генерисао Guid са забетонираном вредношћу (све нуле су у питању - 32 цифре су 0). Није ми хтело радити другачије. Ако мислиш да може ово боље, пробај узети ову грану и вратити је донекле на старо и тако тестирати јел валидно. Мени се чинило да није, али саветујем да пробате.

2022-01-10 17:23 UTC, lemara98 commented on WebShop/WebShop.Frontend/Frontend/src/pages/Cart.js
> +    axios.post(`${BASE_URL}/payment-service/transactions`, listOfOrders, config)
Моја грешка. Објекат се само тако зове listOfOrders. То је у суштини заиста један Order са више ставки.

2022-01-10 17:25 UTC, lemara98 commented on WebShop/WebShop.Service/Services/UserService.cs
> +                new Claim(ClaimTypes.UserData, userDTO.MerchantId)
Ставио сам да се за сваког шаље merchantId шаље за сваког User-a без обзира на улогу јер смо дискутовали да један user на Webshopu може бити реално и продавац и купац у исто време, изузимајући случај да може да купи од самог себе осим ако није тешки перач пара. 😂

2022-01-12 17:51 UTC, AnLong98 approved these changes

2022-01-12 21:44 UTC, merged